workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      java: 17
      vars:
        ANDROID_SDK_TOOLS: "10406996_latest"
    scripts:
      - name: Clean Gradle Cache
        script: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf /tmp/gradle-*
          echo "Gradle cache cleared"
      - name: Install Android SDK Tools
        script: |
          mkdir -p /tmp/android-sdk/cmdline-tools/latest
          wget --retry-connrefused --waitretry=1 --timeout=20 -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}.zip
          unzip commandlinetools.zip -d /tmp/android-sdk/cmdline-tools/latest
          mv /tmp/android-sdk/cmdline-tools/latest/cmdline-tools/* /tmp/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=/tmp/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34"
      - name: Debug Java Environment
        script: |
          java -version
          echo $JAVA_HOME
          ls -l /Library/Java/JavaVirtualMachines/
      - name: Install Gradle 8.3
        script: |
          echo "Starting Gradle 8.3 download"
          wget --retry-connrefused --waitretry=1 --timeout=20 -O gradle-8.3-all.zip https://services.gradle.org/distributions/gradle-8.3-all.zip
          echo "Download complete, starting unzip"
          unzip -o gradle-8.3-all.zip -d /tmp
          echo "Unzip complete"
          export GRADLE_HOME=/tmp/gradle-8.3
          export PATH=$GRADLE_HOME/bin:$PATH
          gradle --version
          echo "Gradle installation complete"
      - name: Generate Gradle Wrapper
        script: |
          if [ -f gradle/wrapper/gradle-wrapper.properties ] && [ -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Using existing Gradle wrapper files from repository"
          else
            echo "Generating Gradle wrapper"
            /tmp/gradle-8.3/bin/gradle wrapper --gradle-version 8.3 --distribution-type all
            echo "Wrapper generated with Gradle 8.3"
          fi
      - name: Set Execute Permissions
        script: |
          if [ -f gradlew ]; then
            chmod +x ./gradlew
            echo "Execute permissions set for gradlew"
          else
            echo "Error: gradlew not found"
            exit 1
          fi
      - name: Check Gradle Environment
        script: |
          java -version
          ./gradlew --version
          ls -l
          ls -l gradle/wrapper/
          cat gradle/wrapper/gradle-wrapper.properties
      - name: Clean Build Cache
        script: |
          ./gradlew cleanBuildCache
          echo "Build cache cleared"
      - name: Debug Resources
        script: |
          ls -l app/src/main/res/
          ls -l app/src/main/res/mipmap-anydpi-v26/
          cat app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
          cat app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
          cat app/src/main/res/values/themes.xml
      - name: Debug Dependencies
        script: |
          echo "Running gradlew :app:dependencies"
          ./gradlew :app:dependencies --stacktrace --warn
          echo "Dependencies debug complete"
      - name: Debug Kotlin Compilation
        script: |
          ./gradlew :app:compileDebugKotlin --stacktrace --warn
      - name: Build Debug APK
        script: |
          ./gradlew :app:assembleDebug --stacktrace --warn
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
