# Stand: 2025-05-22_01:39
workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - android
      java: 17
      vars:
        ANDROID_SDK_TOOLS: "10406996_latest"
        GRADLE_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"
    scripts:
      - name: Install Android SDK Tools
        script: |
          mkdir -p /tmp/android-sdk/cmdline-tools/latest
          wget --retry-connrefused --waitretry=1 --timeout=20 -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}.zip
          unzip commandlinetools.zip -d /tmp/android-sdk/cmdline-tools/latest
          mv /tmp/android-sdk/cmdline-tools/latest/cmdline-tools/* /tmp/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=/tmp/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34"
      - name: Setup Java Environment
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
      - name: Install Gradle 8.7
        script: |
          wget --retry-connrefused --waitretry=1 --timeout=20 -O gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -o gradle-8.7-bin.zip -d /tmp
          export GRADLE_HOME=/tmp/gradle-8.7
          export PATH=$GRADLE_HOME/bin:$PATH
          gradle --version
      - name: Generate Gradle Wrapper
        script: |
          echo "Generating Gradle wrapper"
          /tmp/gradle-8.7/bin/gradle wrapper --gradle-version 8.7 --distribution-type bin
          ls -l gradle/wrapper/
      - name: Set Execute Permissions
        script: |
          echo "Setting execute permissions for gradlew"
          if [ -f gradlew ]; then
            chmod +x ./gradlew
          else
            echo "Error: gradlew not found"
            exit 1
          fi
      - name: Clean Gradle Cache
        script: |
          echo "Cleaning entire Gradle cache"
          rm -rf ~/.gradle/caches/*
          rm -rf ~/.gradle/wrapper
      - name: Clean Project
        script: |
          echo "Cleaning project"
          ./gradlew clean
      - name: Sync Dependencies
        script: |
          echo "Synchronizing Gradle dependencies"
          ./gradlew build --refresh-dependencies --stacktrace --info
      - name: Build KSP Debug
        script: |
          echo "Running KSP Debug"
          ./gradlew :app:kspDebugKotlin --stacktrace --info
      - name: Build Debug APK
        script: |
          echo "Running assembleDebug"
          ./gradlew assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/generated/ksp/**/* # KSP-generierte Dateien
      - app/schemas/*.json # Schema-Dateien
    publishing:
      email:
        recipients:
          - your-email@example.com # Ersetze mit deiner E-Mail
