workflows:
  android workflow:
    name: Android Build
    environment:
      android_sdk: 34
    scripts:
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
