# Stand: 2025-05-20_23:25
workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      java: 17
      vars:
        ANDROID_SDK_TOOLS: "10406996_latest"
    scripts:
      - name: Clean Gradle and Kotlin Cache
        script: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf ~/.kotlin/
          rm -rf ~/.m2/repository/
          echo "Gradle, Kotlin, Maven caches cleared"
      - name: Install Android SDK Tools
        script: |
          mkdir -p /tmp/android-sdk/cmdline-tools/latest
          wget --retry-connrefused --waitretry=1 --timeout=20 -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}.zip
          unzip commandlinetools.zip -d /tmp/android-sdk/cmdline-tools/latest
          mv /tmp/android-sdk/cmdline-tools/latest/cmdline-tools/* /tmp/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=/tmp/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34"
      - name: Setup Java Environment
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          ls -l /Library/Java/JavaVirtualMachines/
      - name: Install Gradle 8.7
        script: |
          wget --retry-connrefused --waitretry=1 --timeout=20 -O gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -o gradle-8.7-bin.zip -d /tmp
          export GRADLE_HOME=/tmp/gradle-8.7
          export PATH=$GRADLE_HOME/bin:$PATH
          gradle --version
      - name: Generate Gradle Wrapper
        script: |
          echo "Generating Gradle wrapper"
          /tmp/gradle-8.7/bin/gradle wrapper --gradle-version 8.7 --distribution-type bin || exit 1
          ls -l gradle/wrapper/
      - name: Set Execute Permissions
        script: |
          if [ -f gradlew ]; then
            chmod +x ./gradlew
          else
            echo "Error: gradlew not found"
            exit 1
          fi
      - name: Debug Gradle Wrapper
        script: |
          echo "Checking Gradle wrapper integrity"
          ls -l gradle/wrapper/
          if [ -f gradle/wrapper/gradle-wrapper.jar ]; then
            file gradle/wrapper/gradle-wrapper.jar
            du -h gradle/wrapper/gradle-wrapper.jar
            java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain --version
          else
            echo "Error: gradle-wrapper.jar not found"
            exit 1
          fi
      - name: Check Gradle Environment
        script: |
          java -version
          ./gradlew --version
          ls -l gradle/wrapper/
          cat gradle/wrapper/gradle-wrapper.properties
      - name: Sync Dependencies
        script: |
          echo "Synchronizing Gradle dependencies"
          ./gradlew build --refresh-dependencies --stacktrace --info || exit 1
      - name: Debug Kotlin Plugin
        script: |
          echo "Checking Kotlin plugin"
          ./gradlew --version | grep Kotlin
          ./gradlew tasks --all | grep compileDebugKotlin
      - name: Debug Android Plugin
        script: |
          echo "Checking Android Gradle Plugin"
          ./gradlew tasks --all | grep assembleDebug
          if [ -d ~/.m2/repository/com/android/tools/build/ ]; then
            ls -l ~/.m2/repository/com/android/tools/build/
          else
            echo "Error: AGP Maven artifacts not found"
            exit 1
          fi
      - name: Clean Build Cache
        script: |
          echo "Manually cleaning build cache"
          rm -rf ~/.gradle/caches/build-cache-*
          echo "Build cache cleaned manually"
      - name: Debug Resources
        script: |
          ls -l app/src/main/res/
          ls -l app/src/main/res/mipmap-anydpi-v26/
          cat app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
          cat app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
          cat app/src/main/res/values/themes.xml
      - name: Debug Dependencies
        script: |
          echo "Running dependencies check"
          ./gradlew :app:dependencies --stacktrace --info
      - name: Debug Kotlin Compilation
        script: |
          echo "Running Kotlin compilation"
          ./gradlew :
