# Timestamp: 2025-05-22 23:58:00 CEST
# codemagic.yaml
workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - android
      java: 17
      vars:
        ANDROID_SDK_TOOLS: "10406996_latest"
        GRADLE_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"
    scripts:
      - name: Install Android SDK Tools
        script: |
          mkdir -p /tmp/android-sdk/cmdline-tools/latest
          wget --retry-connrefused --waitretry=1 --timeout=20 -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}.zip
          unzip commandlinetools.zip -d /tmp/android-sdk/cmdline-tools/latest
          mv /tmp/android-sdk/cmdline-tools/latest/cmdline-tools/* /tmp/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=/tmp/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34"
      - name: Setup Java Environment
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
      - name: Install Gradle 8.9
        script: |
          wget --retry-connrefused --waitretry=1 --timeout=20 -O gradle-8.9-all.zip https://services.gradle.org/distributions/gradle-8.9-all.zip
          unzip -o gradle-8.9-all.zip -d /tmp
          export GRADLE_HOME=/tmp/gradle-8.9
          export PATH=$GRADLE_HOME/bin:$PATH
          gradle --version
      - name: Clean Gradle Cache
        script: |
          echo "Cleaning entire Gradle cache"
          rm -rf ~/.gradle/*
      - name: Verify Plugin Repositories
        script: |
          echo "Verifying plugin repositories"
          /tmp/gradle-8.9/bin/gradle --init-script <(echo "initscript { repositories { google(); mavenCentral(); gradlePluginPortal() } }") --version
      - name: Generate Gradle Wrapper
        script: |
          echo "Generating Gradle wrapper"
          /tmp/gradle-8.9/bin/gradle wrapper --gradle-version 8.9 --distribution-type all
          ls -l gradle/wrapper/
          cat gradle/wrapper/gradle-wrapper.properties
          ls -l gradlew
      - name: Set Execute Permissions
        script: |
          echo "Setting execute permissions for gradlew"
          if [ -f gradlew ]; then
            chmod +x ./gradlew
            ls -l gradlew
          else
            echo "Error: gradlew not found"
            exit 1
          fi
      - name: Verify Gradle Setup
        script: |
          echo "Verifying Gradle setup"
          ./gradlew --version
          echo "Checking available tasks"
          ./gradlew help --task tasks || echo "Failed to list tasks"
          ./gradlew help --task clean || echo "Failed to find clean task"
          ./gradlew help --task build || echo "Failed to find build task"
          ./gradlew help --task assembleDebug || echo "Failed to find assembleDebug task"
          ./gradlew projects || echo "Failed to list projects"
      - name: Clean Project
        script: |
          echo "Cleaning project"
          ./gradlew clean --stacktrace --info || echo "Clean task failed"
      - name: Sync Dependencies
        script: |
          echo "Synchronizing Gradle dependencies"
          ./gradlew dependencies --stacktrace --info || echo "Dependencies task failed"
      - name: Build KSP Debug
        script: |
          echo "Running KSP Debug"
          echo "Preparing schema directory"
          mkdir -p app/schemas
          chmod -R u+w app/schemas
          ls -ld app/schemas
          ./gradlew :app:kspDebugKotlin --stacktrace --info
          echo "Verifying Room schema"
          ./gradlew verifyRoomSchema --stacktrace --info || echo "Schema verification failed"
          echo "Checking schema files"
          ls -l app/schemas/ || echo "No schema files found"
          if [ -d app/schemas/com.example.testapp.data.AppDatenbank ]; then
              echo "Found unexpected schema directory"
              ls -l app/schemas/com.example.testapp.data.AppDatenbank/
          fi
          if [ -f app/schemas/1.json ]; then
              echo "Schema file 1.json found"
              cat app/schemas/1.json
              wc -l app/schemas/1.json
          else
              echo "Schema file 1.json not generated"
          fi
          echo "Checking KSP generated files"
          ls -l app/build/generated/ksp/debug/kotlin/ || echo "No KSP generated files found"
          find app/build/generated/ksp/debug/ -type f
          echo "Searching for schema files in entire project"
          find . -name "*.json"
      - name: Build Debug APK
        script: |
          echo "Running assembleDebug"
          ./gradlew assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/generated/ksp/**/*
      - app/schemas/*.json
    publishing:
      email:
        recipients:
          - mafi82290@online.de
