# Stand: 2025-05-22_00:23
workflows:
  android-build:
    name: Android Build
    environment:
      groups:
        - android
      vars:
        GRADLE_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"
    scripts:
      - name: Clean Build Cache
        script: |
          ./gradlew cleanBuildCache
          rm -rf ~/.gradle/caches
      - name: Generate Gradle Wrapper
        script: |
          ./gradlew wrapper
      - name: Build Debug
        script: |
          ./gradlew :app:kspDebugKotlin --info
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/generated/ksp/**/*
      - app/schemas/*.json
    publishing:
      email:
        recipients:
          - your-email@example.com
