workflows:
  android-workflow:
    name: Android Workflow
    environment:
      groups:
        - android
      vars:
        CM_BUILD_DIR: $CM_BUILD_DIR
      android_signing:
        - keystore
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          ./gradlew wrapper
      - name: Build Debug APK
        script: |
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
